<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= \Mileena\CrmSkeleton\App::getInstance()->config->get('app.crm_name');?></title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/flatly/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/assets/css/style.css">


    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/js/equip.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="/"><i class="bi bi-box-seam"></i> <?= \Mileena\CrmSkeleton\App::getInstance()->config->get('app.crm_name');?></a>

        <?php
        if (\Mileena\Web\Auth::isAuth()) : ?>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar"
                    aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainNavbar">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item"><a class="nav-link" href="/manager/">Менеджеры</a></li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">

                        <a class="nav-link" href="/manager/edit?id=<?=
                        \Mileena\Web\Auth::getUserId() ?>" title="Профиль">
                            <i class="bi bi-person-circle"></i>
                            <?= htmlspecialchars(\Mileena\Web\Auth::getUsername() ?? '') ?>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/manager/logout" title="Выход">
                            <i class="bi bi-box-arrow-right"></i> Выход
                        </a>
                    </li>
                </ul>
            </div>
        <?php
        endif; ?>
    </div>
</nav>
